name: HotDog
options:
  bundleIdPrefix: com.darrylcauldwell
  deploymentTarget:
    iOS: "16.0"
  generateEmptyDirectories: true

targets:
  HotDog:
    type: application
    platform: iOS
    sources:
      - path: HotDog
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_FILE: HotDog/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.darrylcauldwell.HotDog
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_STRICT_CONCURRENCY: targeted
    dependencies:
      - sdk: Vision.framework
      - sdk: CoreML.framework
