name: SeeFood
options:
  bundleIdPrefix: dev.dreamfold
  deploymentTarget:
    iOS: "16.0"
  generateEmptyDirectories: true

targets:
  SeeFood:
    type: application
    platform: iOS
    sources:
      - path: SeeFood
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_FILE: SeeFood/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: dev.dreamfold.HotDog
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_STRICT_CONCURRENCY: targeted
    dependencies:
      - sdk: Vision.framework
      - sdk: CoreML.framework
